### PR TITLE
Meter log drain

### PR DESCRIPTION
**Pull request by rjschwei**
Fixes a couple of issues with registration sharing.

### CODE REVIEW

**Comment by rjschwei** [comment]
@ikapelyukhin any comments?

**Comment by ikapelyukhin** [comment]
@rjschwei I'm not sure if blocking the whole app with `sleep 1;` is a good idea. I'd personally put all the records in the beginning into `@undeliverdRecords`, and then deliver small chunks of data each time `_sharePreviousRegistrations` is called (although I'm not sure how often it is called).
But only you are using that functionality, so if it works for you -- it looks OK otherwise. :-)

**Comment by rjschwei** [comment]
@ikapelyukhin well to the best of my knowledge sleep only effects the thread, this appears to be confirmed by https://stackoverflow.com/questions/32260595/perl-make-thread-sleep. At least this applies to Perl. I am not sure about the behavior within mod_perl but would hope the behavior is the same, i.e. sleep only puts the thread to sleep. Could you please merge?

Are you OK with me submitting 3.0.27 to QA/Maint for release?

**Comment by ikapelyukhin** [comment]
@rjschwei I'm not sure what it does to mod_perl either, I personally would avoid it.
Sure, please feel free to issue the maintenance request.

**Pull request merged**
