### PR TITLE
update usage after --scc and --nosync removal

### PR DESCRIPTION
**Pull request by aaannz**
- remove undeclared $nccreport

### CODE REVIEW

**Comment by jsrain** [comment]
LGTM

**Comment by aaannz** [comment]
added c31684b to remove --scc and --nosync from POD section.
@mcalmer I'm wondering, does this reports anything when --local is not specified?

**Comment by mcalmer** [comment]
I think yes. There are some daily checks (SSL certificate expire) which runs also without local

**Comment by mcalmer** [comment]
Feel free to merge

**Pull request merged**
