### PR TITLE
Add caching code for SCC GUID to startup script 4375

### PR DESCRIPTION
**Pull request by ikapelyukhin**

### CODE REVIEW

**Comment by mcalmer** [comment]
Hmm, what happens if you call this multiple times. Will you get more and more CACHE sections?

Other option would be to write a small tool which read the username and dump it in a new file below /var/cache/... . The smt-maintenance script just call this tool.

**Comment by ikapelyukhin** [comment]
I've rebased the branch, the code should be much less weird now.

**Comment by suse-tests-pass** [comment]
@fschueller will review your pull request :dancers: check https://trello.com/c/5sDvxKdd/4375-fix-scccredentials-permissions-issue-in-smt
  @fschueller: Please review this pull request using our guidelines:
  * test for acceptance criteria / functionality
  * check if the new code is covered with tests
  * check for unintended consequences
  * encourage usage of the boyscout rule
  * make sure the code is architected in the best way
  * check that no unnecessary technical debt got introduced
  * make sure that no unnecessary FIXMEs or TODOs got added

**Comment by fschueller** [comment]
lgtm

**Pull request merged**
