### PR TITLE
Smt12 rollback

### PR DESCRIPTION
**Pull request by mcalmer**
Implement synchronize call needed for rollback

### CODE REVIEW

**Comment by mcalmer** [comment]
@aaannz @jsrain : you might want to have a look at this.

**Comment by jsrain** [comment]
Hard to comment not knowing the internals of SMT itself. Don't see any obvious problem, though.

**Comment by aaannz** [comment]
LGTM

**Comment by mcalmer** [comment]
@aaannz : merged. I think you take care of a new submission to SP1, right?

**Comment by aaannz** [comment]
sure, I want to include #45 too in this version bump

**Comment by jsrain** [comment]
I will not be able to perform testing today, but will test it next week (after the SUSE summer event), afterwards I think it can be backported to 11-SP3 and passed to maintenance.

**Comment by mcalmer** [comment]
@jsrain :  Devel:SMT:SLE-11-SMT-SP3/smt has it already. So we are ready to submit it as maintenance update.
But the old one is not yet QAed.

**Pull request merged**
