### PR TITLE
limit timestamp to 32bit value (bnc#945382)

### PR DESCRIPTION
**Pull request by aaannz**

### CODE REVIEW

**Comment by aaannz** [comment]
@mcalmer I don't have access to my test machine (WOL is not working, sadly) so I didn't test it. But should workaround 32bit time issue. What do you think?

**Comment by mcalmer** [comment]
I think we should give it a try. We are here only on 64 Bit systems. So I hope that $time do not get negative.

Good to merge.

**Comment by aaannz** [comment]
Sadly the log doesn't work as I thought and $log and $vblevel variables aren't global. So I can't use printLog without making other significant changes.
Would it be ok to print the warning on stderr? Or just silently alter the end date. I'm also wondering about usability of this message since it doesn't tell to which product/subscription it is related, so maybe doing this silently is not so bad.

**Comment by mcalmer** [comment]
As a quick fix it would be ok to silently change it without message.
If we log on stderr, every customer who hit this will complain.

Other solution: add optional $log and $vblevel to this function. If they exists, you can log, otherwise not.
And then we change one place where we load the subscriptions and provide these two parameter to the function.
A little bit hacky, but we would have a logmessage.

**Comment by aaannz** [comment]
I just removed the log for now. I don't have facility to properly test it here.

**Pull request merged**
