### PR TITLE
send and empty obsoleted_service_name with the upgrade result

### PR DESCRIPTION
**Pull request by mcalmer**
@jsrain , @aaannz from a discussion about the rollback

### CODE REVIEW

**Comment by aaannz** [comment]
LGTM, but I have only vague idea what it is for :)

**Comment by jsrain** [comment]
Looks good, but the registration gem fails to handle empty string even though it is what they asked for. I would wait until they clarify what they really need, but since the value is passed without any check through the classes of the registration gem, I'm pretty sure that this is something the SCC team needs to fix.

**Comment by mcalmer** [comment]
@jsrain : If you have your testsetup please try out if this works

**Comment by mcalmer** [comment]
According to http://bugzilla.novell.com/show_bug.cgi?id=948551#c7 I will merge it

**Comment by mcalmer** [comment]
@aaannz : will you handle the submission to SLES12 SP1, or should I do ?

**Comment by aaannz** [comment]
I'll do it. I have already prepared changes and version bump.

**Pull request merged**
