### PR TITLE
remove smt-mirror-sle9 (fate#319415)

### PR DESCRIPTION
**Pull request by aaannz**

### CODE REVIEW

**Comment by aaannz** [comment]
@jsrain @mcalmer any comments?

**Comment by mcalmer** [comment]
@aaannz : Please check config/smt.conf.production and config/smt.conf

Both have the configuration for SLE9. All Sections starting with 

[YOU9-.....

can be removed too.

**Comment by aaannz** [comment]
rebased and added de4487e which removes SLE9 from configs

**Comment by mcalmer** [comment]
LGTM

**Pull request merged**
