### PR TITLE
upgrade from SMT11 does not preserve SCCcredentials permissions (bsc#…

### PR DESCRIPTION
**Pull request by aaannz**
…943568)

- read permissions for smt is now checked and set each time smt-maintenance is
  run

### CODE REVIEW

**Comment by aaannz** [comment]
@jsrain @mcalmer please take a look.

**Comment by mcalmer** [comment]
Do we have on SLES12 any supported filesystem which does not support ACLs ?

**Comment by jsrain** [comment]
@mcalmer I would be really surprised, we used ACLs on SLE11 and I'm not aware of any problems with that.
Besides this discussion, the patch looks OK.

**Comment by mcalmer** [comment]
@jsrain : well on SLES11 we check after setfacl if we can access with smt user. If not we do a

 chown smt.root /etc/zypp/credentials.d/NCCcredentials

This is the reason why I ask.

It would be much easier if we define "you must use a FS with ACL support for /etc" .
For me it would be a "go" as well.

**Comment by aaannz** [comment]
according to setfacl manpage, when ACLs are not available it tries to set regular permissions. But how does it work exactly I don't know yet. I'll try to check on one test machine.

**Comment by aaannz** [comment]
Tested hypothesis from comment#5, but it didn't hold. setfacl just reported error and changed nothing if ACLs are not available. However I'm wondering if just changing owner is good way to go. I would rather report an error and let admin to fix permissions manually.
I think, by default, ACLs are on btrfs, xfs, ext4 so there is good chance setfacl will work on most deployments.

**Comment by mcalmer** [comment]
Agree.  Feel free to merge

**Pull request merged**
