### PR TITLE
do not use removed --nosync option (bsc#944693)

### PR DESCRIPTION
**Pull request by aaannz**
- also remove mentions about removed options

### CODE REVIEW

**Comment by mcalmer** [comment]
@aaannz : not sure if you want to remove --local. You can do if you want.

Otherwise the commit is ok.

**Comment by aaannz** [comment]
Ok, I'll make --local default mode and remove the option.

**Comment by aaannz** [comment]
added 1b8eb26 removing --local

**Comment by mcalmer** [comment]
LGTM

**Pull request merged**
